"""
    Even Fibonacci numbers

    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""

def calc_even_fib_until(number):
    a = 0
    b = 1
    sum = 0
    while b < number:
        aa = a
        a = b
        b = b + aa
        if a % 2 == 0:
            sum += a
    return sum

if __name__ == "__main__":
    print(calc_even_fib_until(4000000))
